#include "TrackingAction.hh"
#include "G4Track.hh"
#include "G4OpticalPhoton.hh"
#include "G4Electron.hh"
#include "G4VProcess.hh"
#include "G4ios.hh"
#include "G4RunManager.hh"
#include "EventAction.hh"
#include "G4SystemOfUnits.hh"

#include "HistoManager.hh"


TrackingAction::TrackingAction() : G4UserTrackingAction()
{
}

TrackingAction::~TrackingAction()
{
    // ftracksFile ->Write();
    // ftracksFile->Close();
    // delete ftracksFile;
    // ftracksFile = nullptr;
}

void TrackingAction::PreUserTrackingAction(const G4Track* track)
{
    // if(track->GetDefinition() == G4OpticalPhoton::OpticalPhotonDefinition())
    // {
    //     if(!ftracksFile)
    //     {
    //         ftracksFile = new TFile("tracks.root", "RECREATE");
    //         ftracksTree = new TTree("tracks", "Photon Tracks");
    //         ftracksTree->Branch("creatorProcess", &fCreatorProcess, "creatorProcess/I");
    //         ftracksTree->Branch("CreatedPhotonEnergy", &fPhotonEnergy, "CreatedPhotonEnergy/D");
    //         ftracksTree->Branch("EventID", &fEventID, "EventID/I");
    //         ftracksTree->Branch("pType", &fparticletype, "pType/I");
    //     }
    //     fparticletype = 1;
        
    //     const G4VProcess* proc = track->GetCreatorProcess();
    //     G4String name = proc ? proc->GetProcessName() : "unknown";

        
    //     if(name == "Scintillation") fCreatorProcess = 1;
    //     if(name == "Cerenkov") fCreatorProcess = 2;
    //     if(name != "Scintillation" && name != "Cerenkov") 
    //     {
    //         fCreatorProcess = 3;
    //         G4cout << "TrackID :" << track->GetTrackID() << " Creator: " << name << G4endl;
    //     }
        
    //     fPhotonEnergy = track->GetKineticEnergy() / eV;

    //     fEventID = G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID();

    //     ftracksTree->Fill();
    // } else if(track->GetDefinition() == G4Electron::ElectronDefinition())
    // {
    //     fEventID =  G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID();
    //     fparticletype = 2;
    //     fPhotonEnergy = track->GetKineticEnergy() /eV;
    //     const G4VProcess* proc = track->GetCreatorProcess();
    //     G4String name = proc ? proc->GetProcessName() : "unknown";
    //     G4cout << "Electron generated by: " << name << G4endl;
    //     ftracksTree->Fill();
    // }
    // if(track->GetDefinition() != G4OpticalPhoton::OpticalPhotonDefinition())
    // {  
    //     G4cout << "TrackID :" << track->GetTrackID() << " Particle: " << track->GetDefinition()->GetParticleName() 
    //            << " Energy: " << track->GetKineticEnergy() / keV << " keV" 
    //            << " Creator: " << (track->GetCreatorProcess() ? track->GetCreatorProcess()->GetProcessName() : "unknown") 
    //            << G4endl;
    // }

    HistoManager::GetPointer()->TrackingAction(track);

}